In [84]:
import numpy as np

In [85]:
#2d array
two_d_arr = np.array([[3,4, 5],[1,2, 0]])
print(two_d_arr)
print(two_d_arr.shape)

[[3 4 5]
 [1 2 0]]
(2, 3)


In [86]:
#3d array
three_d_arr = np.array([[[3,4, 5],[1,'2', 0]], [[36,44, 53],[21,52.89, 70]]])
print(three_d_arr)
print(three_d_arr.shape)

[[['3' '4' '5']
  ['1' '2' '0']]

 [['36' '44' '53']
  ['21' '52.89' '70']]]
(2, 2, 3)


In [87]:
# shape : shape of an array
print("shape of the array = ", two_d_arr.shape)
print("shape of the array = ", three_d_arr.shape)

shape of the array =  (2, 3)
shape of the array =  (2, 2, 3)


In [88]:
# ndim : dimensions of an array
print("Dimenions of the array = ", two_d_arr.ndim)
print("Dimenions of the array = ", three_d_arr.ndim)

Dimenions of the array =  2
Dimenions of the array =  3


In [89]:
#size: total number of elements in the array
print("total number of elements in the array = ", two_d_arr.size)
print("total number of elements in the array = ", three_d_arr.size)

total number of elements in the array =  6
total number of elements in the array =  12


In [90]:
#dtype: Data type of the array
print("Data type of the array = ", two_d_arr.dtype)
print("Data type of the array = ", three_d_arr.dtype)

Data type of the array =  int64
Data type of the array =  <U32


In [91]:
#astype: changes data type of the array
three_d_arr_n = three_d_arr.astype('float64')
print("changes data type of the array = ", three_d_arr_n.dtype)

changes data type of the array =  float64


### Array Manipulations

In [92]:
a = np.random.randint(100,200, (2,3, 4))
print(a)

[[[120 162 110 127]
  [143 127 110 177]
  [191 124 144 108]]

 [[126 197 180 173]
  [119 147 182 176]
  [185 174 129 160]]]


In [93]:
# np.insert(a, 2, 10, axis=0)
np.insert(a, 1, np.random.randint(0,5), axis=1)

array([[[120, 162, 110, 127],
        [  4,   4,   4,   4],
        [143, 127, 110, 177],
        [191, 124, 144, 108]],

       [[126, 197, 180, 173],
        [  4,   4,   4,   4],
        [119, 147, 182, 176],
        [185, 174, 129, 160]]], dtype=int32)

In [94]:
np.append(a,a, axis=1)

array([[[120, 162, 110, 127],
        [143, 127, 110, 177],
        [191, 124, 144, 108],
        [120, 162, 110, 127],
        [143, 127, 110, 177],
        [191, 124, 144, 108]],

       [[126, 197, 180, 173],
        [119, 147, 182, 176],
        [185, 174, 129, 160],
        [126, 197, 180, 173],
        [119, 147, 182, 176],
        [185, 174, 129, 160]]], dtype=int32)

In [95]:
# np.delete(a,(0), axis=0)
# np.delete(a,(0,1), axis=0)

In [102]:
np.unique(a)
# np.unique(a, return_counts=True)
# np.unique(a, return_index=True)
np.unique(a, return_counts=True, return_index=True)

(array([108, 110, 119, 120, 124, 126, 127, 129, 143, 144, 147, 160, 162,
        173, 174, 176, 177, 180, 182, 185, 191, 197], dtype=int32),
 array([11,  2, 16,  0,  9, 12,  3, 22,  4, 10, 17, 23,  1, 15, 21, 19,  7,
        14, 18, 20,  8, 13]),
 array([1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

### Array Operations & Functions

In [133]:
arr1 = np.arange(3)
print(arr1)
print(arr1 + 1)
print("-----------------")
arr2 = np.random.randint(1,10, (3,3))
print(arr2)
print(np.add(arr2 , arr1))
print("-----------------")
print(np.max(arr1))

[0 1 2]
[1 2 3]
-----------------
[[4 9 9]
 [5 9 8]
 [3 4 3]]
[[ 4 10 11]
 [ 5 10 10]
 [ 3  5  5]]
-----------------
2
